insert into rockChildren (id, first_name, last_name, type, color, gender, user_id, quote) values (1, 'Shurwood', 'Barkway', 'light', 3, 'Male', null, 'The clear star that is yesterday would kindly inquire something about you.'),
(2, 'Carmine', 'Challenor', 'medium', 10, 'Bigender', null, 'A cranky old lady comes asking for bread.'),
(3, 'Ernaline', 'Viall', 'medium', 6, 'Female', null, 'I caught my squirrel rustling through my gym bag.'),
(4, 'Simonne', 'Shawl', 'light', 9, 'Female', null, 'After exploring the abandoned building, she started to believe in ghosts.'),
(5, 'Nerta', 'Deely', 'medium', 10, 'Female', null, 'Peanut butter and jelly caused the elderly lady to think about her past.'),
(6, 'Alejandra', 'Pinckney', 'medium', 8, 'Female', null, 'The pigs were insulted that they were named hamburgers.'),
(7, 'Ulick', 'Castagnone', 'dark', 8, 'Male', null, 'Going from child, to childish, to childlike is only a matter of time.'),
(8, 'Clarence', 'Cundict', 'medium', 2, 'Male', null, 'Lets all be unique together until we realise we are all the same.'),
(9, 'Mandie', 'Heinicke', 'light', 6, 'Female', null, 'I''d rather be a bird than a fish.'),
(10, 'Delbert', 'Seres', 'light', 6, 'Male', null, 'Courage and stupidity were all he had.'),
(11, 'Craggy', 'Casley', 'light', 5, 'Male', null, 'The mysterious diary records the voice.'),
(12, 'Luz', 'Pietron', 'light', 10, 'Female', null, 'Sometimes I stare at a door or a wall and I wonder what is this reality, why am I alive, and what is this all about?'),
(13, 'Gibb', 'Stabler', 'dark', 2, 'Male', null, 'He had a hidden stash underneath the floorboards in the back room of the house.'),
(14, 'Dunstan', 'Longo', 'medium', 1, 'Male', null, 'Flesh-colored yoga pants were far worse than even he feared.'),
(15, 'Esta', 'Bernhardi', 'light', 10, 'Female', null, 'She had reached the point where she was paranoid about being paranoid.'),
(16, 'Selma', 'Willes', 'dark', 10, 'Female', null, 'The Guinea fowl flies through the air with all the grace of a turtle.'),
(17, 'Val', 'Jamot', 'light', 1, 'Male', null, 'The secret ingredient to his wonderful life was crime.'),
(18, 'Fabiano', 'Swindlehurst', 'dark', 9, 'Male', null, 'Pink horses galloped across the sea.'),
(19, 'Lizzie', 'Lilliman', 'light', 1, 'Female', null, 'The tart lemonade quenched her thirst, but not her longing.'),
(20, 'Eddie', 'Dell ''Orto', 'light', 7, 'Female', null, 'Everyone was curious about the large white blimp that appeared overnight.'),
(21, 'Sashenka', 'Daley', 'light', 7, 'Female', null, 'Her mind was blown that there was nothing in space except space itself.'),
(22, 'Cyrill', 'Fieldgate', 'medium', 4, 'Male', null, 'He realized there had been several deaths on this road, but his concern rose when he saw the exact number.'),
(23, 'Pearl', 'Arghent', 'dark', 5, 'Female', null, 'She had some amazing news to share but nobody to share it with.'),
(24, 'Ebony', 'Wiffill', 'medium', 8, 'Genderfluid', null, 'The small white buoys marked the location of hundreds of crab pots.'),
(25, 'Linet', 'Pawelek', 'light', 7, 'Female', null, 'While on the first date she accidentally hit her head on the beam.'),
(26, 'Palm', 'Easen', 'medium', 4, 'Male', null, '8% of 25 is the same as 25% of 8 and one of them is much easier to do in your head.'),
(27, 'Fransisco', 'Bernardoni', 'light', 8, 'Male', null, 'I am happy to take your donation; any amount will be greatly appreciated.'),
(28, 'Shamus', 'Course', 'light', 9, 'Male', null, 'They were excited to see their first sloth.'),
(29, 'Sibbie', 'Chesworth', 'light', 7, 'Female', null, 'Sibble enjoyed eating pancakes with ketchup.'),
(30, 'Inga', 'Nealey', 'light', 2, 'Female', null, 'If I don''t like something, I''ll stay away from it.'),
(31, 'Derby', 'Furmston', 'light', 7, 'Male', null, 'Derby took the deep dive down the rabbit hole.'),
(32, 'Flory', 'Norewood', 'dark', 6, 'Male', null, 'He decided to live his life by the big beats manifesto.'),
(33, 'Berte', 'Capsey', 'light', 9, 'Female', null, 'It took her a month to finish the meal.'),
(34, 'Erastus', 'Shillabeer', 'dark', 10, 'Male', null, 'Pantyhose and heels are an interesting choice of attire for the beach.'),
(35, 'Britt', 'McDoual', 'medium', 9, 'Male', null, 'They got there early, and they got really good seats.'),
(36, 'Haze', 'Madine', 'dark', 4, 'Genderfluid', null, 'Had they known what was going to happen, they would have never stepped into the shower.'),
(37, 'Celia', 'McElwee', 'dark', 1, 'Female', null, 'She invested some skill points in Charisma and Strength.'),
(38, 'Heath', 'Dwelley', 'dark', 4, 'Male', null, 'Now I need to ponder my existence and ask myself if I''m truly real'),
(39, 'Spence', 'Leighton', 'light', 5, 'Male', null, 'He drank life before spitting it out.'),
(40, 'Malinda', 'Antunes', 'light', 7, 'Female', null, 'Malinda wouldn''t have eaten the meal if she had known what it actually was.'),
(41, 'Morgen', 'Luckie', 'dark', 8, 'Male', null, 'There can never be too many cherries on an ice cream sundae.'),
(42, 'Drew', 'Partlett', 'light', 5, 'Male', null, 'Italy is my favorite country; in fact, I plan to spend two weeks there next year.'),
(43, 'Sylvia', 'Braganza', 'light', 7, 'Female', null, 'The efficiency we have at removing trash has made creating trash more acceptable.'),
(44, 'Raddie', 'Brough', 'light', 6, 'Male', null, 'Raddie made the sugar cookies; Susan decorated them.'),
(45, 'Prince', 'Ygou', 'light', 9, 'Male', null, 'When transplanting seedlings, candied teapots will make the task easier.'),
(46, 'Rube', 'Dace', 'dark', 10, 'Male', null, 'He was the type of guy who liked Christmas lights on his house in the middle of July.'),
(47, 'Marin', 'Cawston', 'medium', 2, 'Female', null, 'She walked into the basement with the horror movie from the night before playing in her head.'),
(48, 'Adolpho', 'Janton', 'dark', 1, 'Male', null, 'That was how he came to win $1 million.'),
(49, 'Darbie', 'Gayter', 'light', 3, 'Female', null, 'She found the chocolate covered roaches quite tasty.'),
(50, 'Matthew', 'Warwick', 'light', 3, 'Genderfluid', null, 'They poured rocks in the dungeon of their mind.'),
(51, 'Creigh', 'McHenry', 'medium', 4, 'Male', null, 'All they could see was the blue water surrounding their sailboat.'),
(52, 'Katina', 'Berardt', 'medium', 1, 'Genderfluid', null, 'They were disappointed when they found the beach to be so sandy and the sun so sunny.'),
(53, 'Ingeborg', 'Gallico', 'medium', 5, 'Female', null, 'Happiness can be found in the depths of chocolate pudding.'),
(54, 'Glynn', 'Shuttleworth', 'dark', 10, 'Male', null, 'He found a leprechaun in his walnut shell.'),
(55, 'Bryant', 'Broggelli', 'dark', 9, 'Male', null, 'The thick foliage and intertwined vines made the hike nearly impossible.'),
(56, 'Sloan', 'Iacomo', 'light', 10, 'Non-binary', null, 'It was getting dark, and we weren''t there yet.'),
(57, 'Georas', 'Chomicki', 'light', 5, 'Male', null, 'Even though he thought the world was flat he didn''t see the irony of wanting to travel around the world.'),
(58, 'Theodosia', 'Wadelin', 'dark', 3, 'Female', null, 'The opportunity of a lifetime passed before her as she tried to decide between a cone or a cup.'),
(59, 'Loralee', 'Goodchild', 'light', 7, 'Female', null, 'Getting up at dawn is for the birds.'),
(60, 'Emogene', 'Kleinhaut', 'dark', 2, 'Female', null, 'The tart lemonade quenched her thirst, but not her longing.'),
(61, 'Hamnet', 'Shoveller', 'dark', 10, 'Male', null, 'It took him a month to finish the meal.'),
(62, 'Marvin', 'Imbrey', 'light', 2, 'Male', null, 'Two more days and all his problems would be solved.'),
(63, 'Bev', 'Mixer', 'dark', 9, 'Male', null, 'He found the end of the rainbow and was surprised at what he found there.'),
(64, 'Kyler', 'Lacer', 'dark', 8, 'Male', null, 'Writing a list of random sentences is harder than I initially thought it would be.'),
(65, 'Irma', 'Vairow', 'medium', 7, 'Female', null, 'Irma ran from the giraffe toward the dolphin.'),
(66, 'Timothee', 'Boothroyd', 'light', 6, 'Male', null, 'The light in his life was actually a fire burning all around him.'),
(67, 'Sancho', 'Clubley', 'medium', 8, 'Male', null, 'You''ve been eyeing me all day and waiting for your move like a lion stalking a gazelle in a savannah.'),
(68, 'Dore', 'Grimshaw', 'medium', 9, 'Male', null, 'The best key lime pie is still up for debate.'),
(69, 'Keriann', 'Bovaird', 'dark', 5, 'Female', null, 'Nothing seemed out of place except the washing machine in the bar.'),
(70, 'Goddard', 'Janczak', 'light', 5, 'Male', null, 'I checked to make sure that he was still alive.'),
(71, 'Aron', 'Brockhurst', 'dark', 10, 'Male', null, 'he folded his handkerchief neatly.'),
(72, 'Sunny', 'McCarle', 'medium', 10, 'Female', null, 'Beach-combing replaced wine tasting as her new obsession.'),
(73, 'Briney', 'Essery', 'light', 2, 'Female', null, 'The shooter says goodbye to his love.'),
(74, 'Reinaldo', 'Fareweather', 'dark', 2, 'Male', null, 'The three-year-old girl ran down the beach as the kite flew behind her.'),
(75, 'Tamas', 'Magenny', 'dark', 4, 'Male', null, 'Nobody loves a pig wearing lipstick.'),
(76, 'Alvie', 'Franzolini', 'dark', 2, 'Male', null, 'You can''t compare apples and oranges, but what about bananas and plantains?'),
(77, 'Joellyn', 'Audiss', 'medium', 10, 'Non-binary', null, 'They were sad to hear that fireflies are facing extinction due to artificial light, habitat loss, and pesticides.'),
(78, 'Ellyn', 'Gatman', 'light', 5, 'Female', null, 'She did a happy dance because all of the socks from the dryer matched.'),
(79, 'Maritsa', 'Leedal', 'dark', 8, 'Female', null, 'She is never happy until she finds something to be unhappy about; then, she is overjoyed.'),
(80, 'Cara', 'Matysiak', 'dark', 4, 'Female', null, 'He enjoys practicing his ballet in the bathroom.'),
(81, 'Creight', 'Rodson', 'dark', 10, 'Male', null, 'As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.'),
(82, 'Ericka', 'Cokayne', 'dark', 3, 'Female', null, 'She uses onomatopoeia as a weapon of mental destruction.'),
(83, 'Darius', 'Ioselev', 'medium', 9, 'Male', null, 'Fluffy pink unicorns are a popular status symbol among macho men.'),
(84, 'Laurianne', 'Chettle', 'light', 4, 'Female', null, 'Stop waiting for exceptional things to just happen.'),
(85, 'Mitchel', 'Ovington', 'medium', 2, 'Male', null, 'As the rental car rolled to a stop on the dark road, her fear increased by the moment.'),
(86, 'Geoffrey', 'Gretton', 'light', 10, 'Male', null, 'It was getting dark, and we weren''t there yet.'),
(87, 'Emanuele', 'Garlic', 'medium', 5, 'Male', null, 'The green tea and avocado smoothie turned out exactly as would be expected.'),
(88, 'Tatiana', 'Proback', 'dark', 8, 'Female', null, 'Sometimes you have to just give up and win by cheating.'),
(89, 'Danya', 'Feltham', 'medium', 7, 'Male', null, 'His thought process was on so many levels that he gave himself a phobia of heights.'),
(90, 'Ardath', 'Halfhyde', 'dark', 1, 'Female', null, 'Separation anxiety is what happens when you can''t find your phone.'),
(91, 'Lorette', 'Tiptaft', 'light', 9, 'Female', null, 'Wisdom is easily acquired when hiding under the bed with a saucepan on your head.'),
(92, 'Linus', 'McPeck', 'light', 9, 'Male', null, 'I would have gotten the promotion, but my attendance wasn''t good enough.'),
(93, 'Georgena', 'Jellyman', 'medium', 5, 'Female', null, 'Garlic ice-cream was her favorite.'),
(94, 'Fernanda', 'Le Friec', 'medium', 9, 'Polygender', null, 'They only paint with bold colors; They do not like pastels.'),
(95, 'Saunders', 'Lansberry', 'medium', 9, 'Male', null, 'Rock music approaches at high velocity.'),
(96, 'Jareb', 'Sawdy', 'dark', 2, 'Male', null, 'Nothing is as cautiously cuddly as a pet porcupine.'),
(97, 'Brandon', 'Kisbee', 'light', 8, 'Male', null, 'There''s a message for you if you look up.'),
(98, 'Briano', 'Lembke', 'light', 6, 'Male', null, 'He didn''t want to go to the dentist, yet he went anyway.'),
(99, 'Chrisy', 'Bastiman', 'dark', 2, 'Male', null, 'He didn''t understand why the bird wanted to ride the bicycle.'),
(100, 'Pryce', 'Spurgin', 'light', 10, 'Male', null, 'Eating eggs on Thursday for choir practice was recommended.');